Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -68,6 +68,8 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn -B clean install --file pom.xml
+    - name: Verify JAR file exists
+      run: test -f target/order-service.jar || (echo "JAR file not found! after build" && exit 1)  
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     #- name: Update dependency graph
@@ -82,6 +84,9 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+      - name: Verify JAR file exists
+        run: test -f target/order-service.jar || (echo "JAR file not found! in docker state" && exit 1)
+  
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
@@ -96,7 +101,7 @@ jobs:
         run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
           docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest
-
+        working-directory: /app
       - name: Push Docker Image to Docker Hub
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
